#!/bin/bash
# Sets up a new year for Advent of Code
# Usage: start YEAR

mkdir $1;
cd $1;

for i in $(seq -w 1 25); do
    for j in $(seq -f %02g 1 2); do
        mkdir -p $i/$j;
        touch $i/$j/input.txt;
    done;
done;
